project_id = "uqnvsxbndgitkhenyqya"

[functions]
enabled = true

[functions.generate-itinerary]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.admin-dashboard]
verify_jwt = false
